### PR TITLE
chore: modernize dependencies 

### LINKED ISSUE #31: Bug using passkeys
Using passkeys triggers a error/warning message. This has no real impact on the usability of passkeys themself but should be fixed.

```
[2024-03-18 09:47:38,134][162][140073668225920][ERROR][edumfa.api.lib.postpolicy:351] There was no acceptable client mode in the multi-challenge list. The preferred client mode is set to "interactive". Please check Your policy (['interactive', 'webauthn', 'poll', 'u2f']). Error: list index out of range
```

### PR DESCRIPTION
**Pull request by fritterhoff**
Will prop. drop Python 3.6 and maybe also 3.7 support and introduce python 3.11 and python 3.12 support.

### CODE REVIEW

**Comment by fritterhoff** [comment]
@pmainz, @ekupris and @j-hoff 
Right now not all new scripts get tested - will add some missing tests in the next few weeks, but I would prefer to merge this as a first big chunk. 

At the moment we are running this version in production without any issues. Feel free to add some comments/critic 😁

**Comment by j-hoff** [comment]
@fritterhoff We can try this in our test environment next week and provide feedback

**Review by j-hoff — COMMENTED** [review]
kind of hard to review this because of all the reformatting that was done to almost every file.
would make it easier if the reformatting (without functional changes) was in a separate PR apart from the dependency updates.

**Comment by fritterhoff** [comment]
No Problem. I will extract the reformatting

**Comment by fritterhoff** [comment]
Grrr... extracting the reformating breaks pretty much.

**Review by j-hoff — APPROVED** [review]
looks good

**Review by j-hoff — APPROVED** [review]
fine :)

**Pull request merged**
