### PR TITLE
fix: Improve scripts for Server Ubuntu packages

### PR DESCRIPTION
**Pull request by Luc1412**
This pull request contains improvements for the install, post install and post remove scripts of the server (apache2, nginx) packages, including:
- Improved code formatting and general code improvements
- Fixing inconsistencies between apache2 and nginx scripts
- Improve database migration handling, especially when migrating from privacyidea to edumfa

### CODE REVIEW

**Comment by fritterhoff** [comment]
@Luc1412 thanks. That looks good. I just fixed some whitespace/formatting issues 😁

**Comment by Luc1412** [comment]
Before merging, I'd like to do some tests.

**Comment by fritterhoff** [comment]
Can also undo the whitespace changes ;)

**Comment by fritterhoff** [comment]
Can that be merged now?

**Comment by Luc1412** [comment]
> Can that be merged now?

Unfortunately there is currently still one issue, which causes the database migration to be run twice.

**Comment by j-hoff** [comment]
issue is resolved now

**Review by fritterhoff — APPROVED** [review]

**Comment by Luc1412** [comment]
@fritterhoff btw. I think it makes sense to update the apache2 package and nginx package too. So with every release we also need to update the changelog for the server deb package. Often `* update version number` as changelog is sufficient.

**Comment by fritterhoff** [comment]
Sure. I would not mind at all. Do you want to propose the missing changes? ;)

**Pull request merged**
